# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CampaignStatusEnum(object):

    """Implementation of the 'CampaignStatus' enum.

    Current status of the campaign.

    Attributes:
        CAMPAIGNREQUESTPENDING: TODO: type description here.
        CAMPAIGNREQUESTFAILED: TODO: type description here.
        CAMPAIGNREQUESTQUEUED: TODO: type description here.
        CAMPAIGNCANCELLED: TODO: type description here.
        CAMPAIGNABORTED: TODO: type description here.
        CAMPAIGNFAILED: TODO: type description here.
        CAMPAIGNSCHEDULED: TODO: type description here.
        CAMPAIGNENDED: TODO: type description here.

    """
    CAMPAIGNREQUESTPENDING = 'CampaignRequestPending'

    CAMPAIGNREQUESTFAILED = 'CampaignRequestFailed'

    CAMPAIGNREQUESTQUEUED = 'CampaignRequestQueued'

    CAMPAIGNCANCELLED = 'CampaignCancelled'

    CAMPAIGNABORTED = 'CampaignAborted'

    CAMPAIGNFAILED = 'CampaignFailed'

    CAMPAIGNSCHEDULED = 'CampaignScheduled'

    CAMPAIGNENDED = 'CampaignEnded'

