# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CategoryTypeEnum(object):

    """Implementation of the 'CategoryType' enum.

    Type of the file being uploaded.

    Attributes:
        GENERAL_VALIDATION: TODO: type description here.
        OBSERVABILITY_TEMPLATE: TODO: type description here.
        SWAGGER_SPEC: TODO: type description here.
        DEPENDENT_SERVICE_VALUES: TODO: type description here.
        WORKLOAD_TGZ: TODO: type description here.
        WORKLOAD_VALUE: TODO: type description here.
        WORKLOAD_YAML: TODO: type description here.
        WORKLOAD_TERRAFORM_ZIP: TODO: type description here.
        WORKLOAD_TERRAFORM_TF: TODO: type description here.
        WORKLOAD_TERRAFORM_TFVAR: TODO: type description here.
        WORKFLOW_SOURCE_FILE: TODO: type description here.
        WORKFLOW_INPUT_SCHEMA: TODO: type description here.
        WORKFLOW_TGZ: TODO: type description here.

    """

    GENERAL_VALIDATION = 'GENERAL_VALIDATION'

    OBSERVABILITY_TEMPLATE = 'OBSERVABILITY_TEMPLATE'

    SWAGGER_SPEC = 'SWAGGER_SPEC'

    DEPENDENT_SERVICE_VALUES = 'DEPENDENT_SERVICE_VALUES'

    WORKLOAD_TGZ = 'WORKLOAD_TGZ'

    WORKLOAD_VALUE = 'WORKLOAD_VALUE'

    WORKLOAD_YAML = 'WORKLOAD_YAML'

    WORKLOAD_TERRAFORM_ZIP = 'WORKLOAD_TERRAFORM_ZIP'

    WORKLOAD_TERRAFORM_TF = 'WORKLOAD_TERRAFORM_TF'

    WORKLOAD_TERRAFORM_TFVAR = 'WORKLOAD_TERRAFORM_TFVAR'

    WORKFLOW_SOURCE_FILE = 'WORKFLOW_SOURCE_FILE'

    WORKFLOW_INPUT_SCHEMA = 'WORKFLOW_INPUT_SCHEMA'

    WORKFLOW_TGZ = 'WORKFLOW_TGZ'
