# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClientTypeEnum(object):

    """Implementation of the 'ClientType' enum.

    The category of application client.

    Attributes:
        V2X: TODO: type description here.
        COMPUTERVISION: TODO: type description here.
        MACHINELEARNING: TODO: type description here.
        IOT: TODO: type description here.
        GAMING: TODO: type description here.
        AR: TODO: type description here.
        VR: TODO: type description here.
        ANALYTICS: TODO: type description here.
        ROBOTICS: TODO: type description here.

    """
    V2_X = 'V2X'

    COMPUTERVISION = 'ComputerVision'

    MACHINELEARNING = 'MachineLearning'

    IOT = 'IoT'

    GAMING = 'Gaming'

    AR = 'AR'

    VR = 'VR'

    ANALYTICS = 'Analytics'

    ROBOTICS = 'Robotics'

