# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClusterInfoDetails(object):

    """Implementation of the 'ClusterInfoDetails' model.

    Details of the cluster information.

    Attributes:
        cluster_name (string): Name of the cluster to be used.
        namespace (string): Namespace name inside cluster.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cluster_name": 'clusterName',
        "namespace": 'namespace'
    }

    def __init__(self,
                 cluster_name=None,
                 namespace=None):
        """Constructor for the ClusterInfoDetails class"""

        # Initialize members of the class
        self.cluster_name = cluster_name 
        self.namespace = namespace 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        cluster_name = dictionary.get("clusterName") if dictionary.get("clusterName") else None
        namespace = dictionary.get("namespace") if dictionary.get("namespace") else None
        # Return an object of this model
        return cls(cluster_name,
                   namespace)
