# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClusterProviderEnum(object):

    """Implementation of the 'ClusterProvider' enum.

    Cloud provider.

    Attributes:
        AWS: TODO: type description here.
        GCP: TODO: type description here.
        AZURE: TODO: type description here.

    """

    AWS = 'AWS'

    GCP = 'GCP'

    AZURE = 'AZURE'
