# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClusterTypeEnum(object):

    """Implementation of the 'ClusterType' enum.

    TODO: type enum description here.

    Attributes:
        PUBLICCLOUD: TODO: type description here.
        DATACENTER: TODO: type description here.

    """

    PUBLICCLOUD = 'publicCloud'

    DATACENTER = 'dataCenter'
