# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CSPCompatibilityEnum(object):

    """Implementation of the 'CSPCompatibility' enum.

    Cloud service provider e.g. AWS_PUBLIC_CLOUD, AWS_WL, AWS_OUTPOST,
    AZURE_EDGE, AZURE_PUBLIC_CLOUD.

    Attributes:
        AWS_PUBLIC_CLOUD: TODO: type description here.
        AWS_WL: TODO: type description here.
        AWS_OUTPOST: TODO: type description here.
        AZURE_PUBLIC_CLOUD: TODO: type description here.
        AZURE_EDGE: TODO: type description here.

    """

    AWS_PUBLIC_CLOUD = 'AWS_PUBLIC_CLOUD'

    AWS_WL = 'AWS_WL'

    AWS_OUTPOST = 'AWS_OUTPOST'

    AZURE_PUBLIC_CLOUD = 'AZURE_PUBLIC_CLOUD'

    AZURE_EDGE = 'AZURE_EDGE'
