# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class CSPProfileIdRequest(object):

    """Implementation of the 'CSPProfileIdRequest' model.

    Request to get the Id of the CSP profile.

    Attributes:
        csp_profile_id (string): CSP Profile ID in which service will be
            deployed.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "csp_profile_id": 'cspProfileId'
    }

    _optionals = [
        'csp_profile_id',
    ]

    def __init__(self,
                 csp_profile_id=APIHelper.SKIP):
        """Constructor for the CSPProfileIdRequest class"""

        # Initialize members of the class
        if csp_profile_id is not APIHelper.SKIP:
            self.csp_profile_id = csp_profile_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        csp_profile_id = dictionary.get("cspProfileId") if dictionary.get("cspProfileId") else APIHelper.SKIP
        # Return an object of this model
        return cls(csp_profile_id)
