# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CSPProfileTypeEnum(object):

    """Implementation of the 'CSPProfileType' enum.

    Type of CSP profile.

    Attributes:
        AWS: TODO: type description here.
        AZURE: TODO: type description here.

    """

    AWS = 'AWS'

    AZURE = 'AZURE'
