# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CycleTypeEnum(object):

    """Implementation of the 'CycleType' enum.

    TODO: type enum description here.

    Attributes:
        CYCLEONE: TODO: type description here.
        CYCLETWO: TODO: type description here.

    """
    CYCLEONE = 'cycleone'

    CYCLETWO = 'cycletwo'

