# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DataBackupProviderEnum(object):

    """Implementation of the 'DataBackupProvider' enum.

    Types of data backup provider.

    Attributes:
        AWS: TODO: type description here.
        MINIO: TODO: type description here.

    """

    AWS = 'AWS'

    MINIO = 'MINIO'
