# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DependentServicesTypeEnum(object):

    """Implementation of the 'DependentServicesType' enum.

    List of dependent services type.

    Attributes:
        MY_SERVICE: TODO: type description here.

    """

    MY_SERVICE = 'MY_SERVICE'
