# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.models.pwn_device_id import PWNDeviceId


class DeviceListIP(object):

    """Implementation of the 'DeviceListIP' model.

    TODO: type model description here.

    Attributes:
        device_ids (List[PWNDeviceId]): TODO: type description here.
        ipaddress (str): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "device_ids": 'deviceIds',
        "ipaddress": 'ipAddress'
    }

    def __init__(self,
                 device_ids=None,
                 ipaddress=None):
        """Constructor for the DeviceListIP class"""

        # Initialize members of the class
        self.device_ids = device_ids 
        self.ipaddress = ipaddress 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        device_ids = None
        if dictionary.get('deviceIds') is not None:
            device_ids = [PWNDeviceId.from_dictionary(x) for x in dictionary.get('deviceIds')]
        ipaddress = dictionary.get("ipAddress") if dictionary.get("ipAddress") else None
        # Return an object of this model
        return cls(device_ids,
                   ipaddress)
