# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.m_5g_biaddress_andcustomerinfo import M5gBiaddressAndcustomerinfo
from verizon.models.m_5g_bidevice_id_1 import M5gBideviceId1


class DeviceListWithServiceAddress(object):

    """Implementation of the 'DeviceListWithServiceAddress' model.

    TODO: type model description here.

    Attributes:
        device_id (List[M5gBideviceId1]): TODO: type description here.
        primary_placeofuse (M5gBiaddressAndcustomerinfo): TODO: type
            description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "device_id": 'deviceId',
        "primary_placeofuse": 'primaryPlaceofuse'
    }

    _optionals = [
        'device_id',
        'primary_placeofuse',
    ]

    def __init__(self,
                 device_id=APIHelper.SKIP,
                 primary_placeofuse=APIHelper.SKIP):
        """Constructor for the DeviceListWithServiceAddress class"""

        # Initialize members of the class
        if device_id is not APIHelper.SKIP:
            self.device_id = device_id 
        if primary_placeofuse is not APIHelper.SKIP:
            self.primary_placeofuse = primary_placeofuse 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        device_id = None
        if dictionary.get('deviceId') is not None:
            device_id = [M5gBideviceId1.from_dictionary(x) for x in dictionary.get('deviceId')]
        else:
            device_id = APIHelper.SKIP
        primary_placeofuse = M5gBiaddressAndcustomerinfo.from_dictionary(dictionary.get('primaryPlaceofuse')) if 'primaryPlaceofuse' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(device_id,
                   primary_placeofuse)
