# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class EdsDiscoveryIntent(object):

    """Implementation of the 'EdsDiscoveryIntent' model.

    TODO: type model description here.

    Attributes:
        ue_identity (string): UEIdentity to discover EDS location service.
        ue_identity_type (UEIdentityTypeEnum): Default type for
            ueIdentityType.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ue_identity": 'ueIdentity',
        "ue_identity_type": 'ueIdentityType'
    }

    _optionals = [
        'ue_identity',
        'ue_identity_type',
    ]

    def __init__(self,
                 ue_identity=APIHelper.SKIP,
                 ue_identity_type='IPAddress'):
        """Constructor for the EdsDiscoveryIntent class"""

        # Initialize members of the class
        if ue_identity is not APIHelper.SKIP:
            self.ue_identity = ue_identity 
        self.ue_identity_type = ue_identity_type 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        ue_identity = dictionary.get("ueIdentity") if dictionary.get("ueIdentity") else APIHelper.SKIP
        ue_identity_type = dictionary.get("ueIdentityType") if dictionary.get("ueIdentityType") else 'IPAddress'
        # Return an object of this model
        return cls(ue_identity,
                   ue_identity_type)
