# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class EnablePromoExp(object):

    """Implementation of the 'enablePromoExp' model.

    TODO: type model description here.

    Attributes:
        enable_promo_exp (bool): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "enable_promo_exp": 'enablePromoExp'
    }

    _optionals = [
        'enable_promo_exp',
    ]

    def __init__(self,
                 enable_promo_exp=APIHelper.SKIP):
        """Constructor for the EnablePromoExp class"""

        # Initialize members of the class
        if enable_promo_exp is not APIHelper.SKIP:
            self.enable_promo_exp = enable_promo_exp 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        enable_promo_exp = dictionary.get("enablePromoExp") if "enablePromoExp" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(enable_promo_exp)
