# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class K8sVersionEnum(object):

    """Implementation of the 'K8sVersion' enum.

    Version of K8s platform.

    Attributes:
        ENUM_115: TODO: type description here.
        ENUM_116: TODO: type description here.
        ENUM_117: TODO: type description here.
        ENUM_118: TODO: type description here.
        ENUM_121: TODO: type description here.

    """

    ENUM_115 = '1.15'

    ENUM_116 = '1.16'

    ENUM_117 = '1.17'

    ENUM_118 = '1.18'

    ENUM_121 = '1.21'
