# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.m_5g_biaccount_nameobject import M5gBiaccountNameobject


class M5gBideviceDetailsresponse(object):

    """Implementation of the '5gbideviceDetailsresponse' model.

    TODO: type model description here.

    Attributes:
        has_more_data (bool): TODO: type description here.
        devices (List[M5gBiaccountNameobject]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "has_more_data": 'hasMoreData',
        "devices": 'devices'
    }

    _optionals = [
        'has_more_data',
        'devices',
    ]

    def __init__(self,
                 has_more_data=APIHelper.SKIP,
                 devices=APIHelper.SKIP):
        """Constructor for the M5gBideviceDetailsresponse class"""

        # Initialize members of the class
        if has_more_data is not APIHelper.SKIP:
            self.has_more_data = has_more_data 
        if devices is not APIHelper.SKIP:
            self.devices = devices 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        has_more_data = dictionary.get("hasMoreData") if "hasMoreData" in dictionary.keys() else APIHelper.SKIP
        devices = None
        if dictionary.get('devices') is not None:
            devices = [M5gBiaccountNameobject.from_dictionary(x) for x in dictionary.get('devices')]
        else:
            devices = APIHelper.SKIP
        # Return an object of this model
        return cls(has_more_data,
                   devices)
