# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.device_list import DeviceList
from verizon.models.primary_place_of_use import PrimaryPlaceOfUse


class ProfileRequest(object):

    """Implementation of the 'ProfileRequest' model.

    TODO: type model description here.

    Attributes:
        devices (list of DeviceList): TODO: type description here.
        carrier_name (string): TODO: type description here.
        account_name (string): TODO: type description here.
        service_plan (string): TODO: type description here.
        mdn_zip_code (string): TODO: type description here.
        primary_place_of_use (list of PrimaryPlaceOfUse): TODO: type
            description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "devices": 'devices',
        "carrier_name": 'carrierName',
        "account_name": 'accountName',
        "service_plan": 'servicePlan',
        "mdn_zip_code": 'mdnZipCode',
        "primary_place_of_use": 'primaryPlaceOfUse'
    }

    _optionals = [
        'devices',
        'carrier_name',
        'account_name',
        'service_plan',
        'mdn_zip_code',
        'primary_place_of_use',
    ]

    def __init__(self,
                 devices=APIHelper.SKIP,
                 carrier_name=APIHelper.SKIP,
                 account_name=APIHelper.SKIP,
                 service_plan=APIHelper.SKIP,
                 mdn_zip_code=APIHelper.SKIP,
                 primary_place_of_use=APIHelper.SKIP):
        """Constructor for the ProfileRequest class"""

        # Initialize members of the class
        if devices is not APIHelper.SKIP:
            self.devices = devices 
        if carrier_name is not APIHelper.SKIP:
            self.carrier_name = carrier_name 
        if account_name is not APIHelper.SKIP:
            self.account_name = account_name 
        if service_plan is not APIHelper.SKIP:
            self.service_plan = service_plan 
        if mdn_zip_code is not APIHelper.SKIP:
            self.mdn_zip_code = mdn_zip_code 
        if primary_place_of_use is not APIHelper.SKIP:
            self.primary_place_of_use = primary_place_of_use 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        devices = None
        if dictionary.get('devices') is not None:
            devices = [DeviceList.from_dictionary(x) for x in dictionary.get('devices')]
        else:
            devices = APIHelper.SKIP
        carrier_name = dictionary.get("carrierName") if dictionary.get("carrierName") else APIHelper.SKIP
        account_name = dictionary.get("accountName") if dictionary.get("accountName") else APIHelper.SKIP
        service_plan = dictionary.get("servicePlan") if dictionary.get("servicePlan") else APIHelper.SKIP
        mdn_zip_code = dictionary.get("mdnZipCode") if dictionary.get("mdnZipCode") else APIHelper.SKIP
        primary_place_of_use = None
        if dictionary.get('primaryPlaceOfUse') is not None:
            primary_place_of_use = [PrimaryPlaceOfUse.from_dictionary(x) for x in dictionary.get('primaryPlaceOfUse')]
        else:
            primary_place_of_use = APIHelper.SKIP
        # Return an object of this model
        return cls(devices,
                   carrier_name,
                   account_name,
                   service_plan,
                   mdn_zip_code,
                   primary_place_of_use)
