# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ProfileStatusFilterEnum(object):

    """Implementation of the 'ProfileStatusFilter' enum.

    The last status of the device's profile as a filter.

    Attributes:
        ENABLE: TODO: type description here.
        DISABLE: TODO: type description here.
        DOWNLOAD_DISABLE: TODO: type description here.
        DOWNLOAD_ENABLE: TODO: type description here.
        NOT_DOWNLOADED: TODO: type description here.
        UNKNOWN: TODO: type description here.
        DELETE: TODO: type description here.

    """
    ENABLE = 'ENABLE'

    DISABLE = 'DISABLE'

    DOWNLOAD_DISABLE = 'DOWNLOAD_DISABLE'

    DOWNLOAD_ENABLE = 'DOWNLOAD_ENABLE'

    NOT_DOWNLOADED = 'NOT_DOWNLOADED'

    UNKNOWN = 'UNKNOWN'

    DELETE = 'DELETE'

