# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RepositoryReacheabilityEnum(object):

    """Implementation of the 'RepositoryReacheability' enum.

    Reachability can be of two types, Internet and Private Network.

    Attributes:
        INTERNET: TODO: type description here.
        ENUM_PRIVATE NETWORK: TODO: type description here.

    """

    INTERNET = 'Internet'

    ENUM_PRIVATE_NETWORK = 'Private Network'
