# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ServiceStateEnum(object):

    """Implementation of the 'ServiceState' enum.

    Defines state of service.

    Attributes:
        DRAFT: TODO: type description here.
        DESIGN: TODO: type description here.
        TESTING: TODO: type description here.
        PUBLISH: TODO: type description here.
        CERTIFY: TODO: type description here.
        READY_TO_USE: TODO: type description here.
        DEPRECATE: TODO: type description here.
        DELETED: TODO: type description here.

    """

    DRAFT = 'DRAFT'

    DESIGN = 'DESIGN'

    TESTING = 'TESTING'

    PUBLISH = 'PUBLISH'

    CERTIFY = 'CERTIFY'

    READY_TO_USE = 'READY_TO_USE'

    DEPRECATE = 'DEPRECATE'

    DELETED = 'DELETED'
