# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class ServiceLaunchHelmYamlGitTag(object):

    """Implementation of the 'ServiceLaunchHelmYamlGitTag' model.

    TODO: type model description here.

    Attributes:
        tag_name (string): TODO: type description here.
        values_yaml_paths (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tag_name": 'tagName',
        "values_yaml_paths": 'valuesYamlPaths'
    }

    _optionals = [
        'tag_name',
        'values_yaml_paths',
    ]

    def __init__(self,
                 tag_name=APIHelper.SKIP,
                 values_yaml_paths=APIHelper.SKIP):
        """Constructor for the ServiceLaunchHelmYamlGitTag class"""

        # Initialize members of the class
        if tag_name is not APIHelper.SKIP:
            self.tag_name = tag_name 
        if values_yaml_paths is not APIHelper.SKIP:
            self.values_yaml_paths = values_yaml_paths 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        tag_name = dictionary.get("tagName") if dictionary.get("tagName") else APIHelper.SKIP
        values_yaml_paths = dictionary.get("valuesYamlPaths") if dictionary.get("valuesYamlPaths") else APIHelper.SKIP
        # Return an object of this model
        return cls(tag_name,
                   values_yaml_paths)
