# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class ServiceOnboardingHelmYamlGitTag(object):

    """Implementation of the 'ServiceOnboardingHelmYamlGitTag' model.

    TODO: type model description here.

    Attributes:
        tag_name (string): The user can provide tagName to the Helm chart.
        values_yaml_paths (list of string): The user can provide an array of
            values. YAML files paths.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tag_name": 'tagName',
        "values_yaml_paths": 'valuesYamlPaths'
    }

    _optionals = [
        'values_yaml_paths',
    ]

    def __init__(self,
                 tag_name=None,
                 values_yaml_paths=APIHelper.SKIP):
        """Constructor for the ServiceOnboardingHelmYamlGitTag class"""

        # Initialize members of the class
        self.tag_name = tag_name 
        if values_yaml_paths is not APIHelper.SKIP:
            self.values_yaml_paths = values_yaml_paths 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        tag_name = dictionary.get("tagName") if dictionary.get("tagName") else None
        values_yaml_paths = dictionary.get("valuesYamlPaths") if dictionary.get("valuesYamlPaths") else APIHelper.SKIP
        # Return an object of this model
        return cls(tag_name,
                   values_yaml_paths)
