# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class SharePlan(object):

    """Implementation of the 'SharePlan' model.

    TODO: type model description here.

    Attributes:
        from_carrier_code (str): TODO: type description here.
        to_carrier_code (str): TODO: type description here.
        criteria_percentage (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "from_carrier_code": 'fromCarrierCode',
        "to_carrier_code": 'toCarrierCode',
        "criteria_percentage": 'criteriaPercentage'
    }

    _optionals = [
        'from_carrier_code',
        'to_carrier_code',
        'criteria_percentage',
    ]

    def __init__(self,
                 from_carrier_code=APIHelper.SKIP,
                 to_carrier_code=APIHelper.SKIP,
                 criteria_percentage=APIHelper.SKIP):
        """Constructor for the SharePlan class"""

        # Initialize members of the class
        if from_carrier_code is not APIHelper.SKIP:
            self.from_carrier_code = from_carrier_code 
        if to_carrier_code is not APIHelper.SKIP:
            self.to_carrier_code = to_carrier_code 
        if criteria_percentage is not APIHelper.SKIP:
            self.criteria_percentage = criteria_percentage 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        from_carrier_code = dictionary.get("fromCarrierCode") if dictionary.get("fromCarrierCode") else APIHelper.SKIP
        to_carrier_code = dictionary.get("toCarrierCode") if dictionary.get("toCarrierCode") else APIHelper.SKIP
        criteria_percentage = dictionary.get("criteriaPercentage") if dictionary.get("criteriaPercentage") else APIHelper.SKIP
        # Return an object of this model
        return cls(from_carrier_code,
                   to_carrier_code,
                   criteria_percentage)
