# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SortDirectionEnum(object):

    """Implementation of the 'SortDirection' enum.

    Sorts the list in ascending/descending order.

    Attributes:
        ASC: TODO: type description here.
        DESC: TODO: type description here.

    """

    ASC = 'ASC'

    DESC = 'DESC'
