# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SourceCodeTypeEnum(object):

    """Implementation of the 'SourceCodeType' enum.

    Source code type can be JAVA or GO.

    Attributes:
        JAVA: TODO: type description here.
        GO: TODO: type description here.

    """

    JAVA = 'JAVA'

    GO = 'GO'
