# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status1Enum(object):

    """Implementation of the 'Status1' enum.

    TODO: type enum description here.

    Attributes:
        SUCCESS: TODO: type description here.
        FAILED: TODO: type description here.

    """
    SUCCESS = 'success'

    FAILED = 'failed'

