# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class UEIdentityTypeEnum(object):

    """Implementation of the 'UEIdentityType' enum.

    Default type for ueIdentityType.

    Attributes:
        IPADDRESS: TODO: type description here.
        MSISDN: TODO: type description here.
        IMEI: TODO: type description here.
        MDN: TODO: type description here.
        GPSI: TODO: type description here.

    """

    IPADDRESS = 'IPAddress'

    MSISDN = 'MSISDN'

    IMEI = 'IMEI'

    MDN = 'MDN'

    GPSI = 'GPSI'
