# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class UpgradeStatusEnum(object):

    """Implementation of the 'UpgradeStatus' enum.

    The status of the upgrades that you want to retrieve.

    Attributes:
        REQUESTPENDING: TODO: type description here.
        QUEUED: TODO: type description here.
        REQUESTFAILED: TODO: type description here.
        INPROGRESS: TODO: type description here.
        FINISHED: TODO: type description here.
        UPGRADEFAILED: TODO: type description here.

    """
    REQUESTPENDING = 'RequestPending'

    QUEUED = 'Queued'

    REQUESTFAILED = 'RequestFailed'

    INPROGRESS = 'InProgress'

    FINISHED = 'Finished'

    UPGRADEFAILED = 'UpgradeFailed'

