# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class UpgradeInfo(object):

    """Implementation of the 'UpgradeInfo' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        edge_id (string): TODO: type description here.
        organization_id (string): TODO: type description here.
        partner_id (string): TODO: type description here.
        created_at (string): TODO: type description here.
        modified_at (string): TODO: type description here.
        nodegroup_id (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "edge_id": 'edge_id',
        "organization_id": 'organization_id',
        "partner_id": 'partner_id',
        "created_at": 'created_at',
        "modified_at": 'modified_at',
        "nodegroup_id": 'nodegroup_id'
    }

    _optionals = [
        'id',
        'edge_id',
        'organization_id',
        'partner_id',
        'created_at',
        'modified_at',
        'nodegroup_id',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 edge_id=APIHelper.SKIP,
                 organization_id=APIHelper.SKIP,
                 partner_id=APIHelper.SKIP,
                 created_at=APIHelper.SKIP,
                 modified_at=APIHelper.SKIP,
                 nodegroup_id=APIHelper.SKIP):
        """Constructor for the UpgradeInfo class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if edge_id is not APIHelper.SKIP:
            self.edge_id = edge_id 
        if organization_id is not APIHelper.SKIP:
            self.organization_id = organization_id 
        if partner_id is not APIHelper.SKIP:
            self.partner_id = partner_id 
        if created_at is not APIHelper.SKIP:
            self.created_at = created_at 
        if modified_at is not APIHelper.SKIP:
            self.modified_at = modified_at 
        if nodegroup_id is not APIHelper.SKIP:
            self.nodegroup_id = nodegroup_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        edge_id = dictionary.get("edge_id") if dictionary.get("edge_id") else APIHelper.SKIP
        organization_id = dictionary.get("organization_id") if dictionary.get("organization_id") else APIHelper.SKIP
        partner_id = dictionary.get("partner_id") if dictionary.get("partner_id") else APIHelper.SKIP
        created_at = dictionary.get("created_at") if dictionary.get("created_at") else APIHelper.SKIP
        modified_at = dictionary.get("modified_at") if dictionary.get("modified_at") else APIHelper.SKIP
        nodegroup_id = dictionary.get("nodegroup_id") if dictionary.get("nodegroup_id") else APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   edge_id,
                   organization_id,
                   partner_id,
                   created_at,
                   modified_at,
                   nodegroup_id)
