# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class WorkloadTypeEnum(object):

    """Implementation of the 'WorkloadType' enum.

    Default service type.

    Attributes:
        CONTAINER: TODO: type description here.
        VIRTUALMACHINE: TODO: type description here.

    """

    CONTAINER = 'container'

    VIRTUALMACHINE = 'virtualMachine'
